name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Extract version from Gradle properties
        run: |
          VERSION=$(./gradlew properties -q --console=plain | grep '^version:' | cut -d ':' -f2- | tr -d ' ')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Build with Gradle Wrapper
        run: ./gradlew :buildPlugin -PbuildType=stable

      - name: Upload artifact
        uses: actions/upload-artifact
        with:
          name: "Opentelemetry-Debug-Log-Viewer-$VERSION.zip"
          path: "Opentelemetry-Debug-Log-Viewer-$VERSION.zip"

      - name: Release with Notes
        uses: softprops/action-gh-release
        with:
          files: |
            ./build/distributions/Opentelemetry-Debug-Log-Viewer-$VERSION.zip
          tag_name: ${{ steps.tag.outputs.release_date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}