name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
permissions:
  contents: write
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
      - name: Build with Gradle Wrapper
        run: ./gradlew :buildPlugin -PbuildType=stable
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: build/distributions
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest_dev"
#          prerelease: true
#          title: "Development Build"
#          files: |
#            build/distributions/*
#        id: "automatic_releases"