name: Java CI with Gradle

on:
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "*" ]
permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build plugin
        uses: eskatos/gradle-command-action@v1.4.0
        with:
          arguments: buildPlugin --stacktrace -PbuildType=stable

      - name: Unpack Distribution
        shell: pwsh
        run: scripts/Unpack-Distribution.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.4
        with:
          name: SpecFlowPlugin
          path: build/distributions/unpacked